<a href="https://colab.research.google.com/github/Meemansha-spec/EDA-with-Pandas/blob/main/Churn_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from overrides.typing_utils import unknown

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
churn_data = pd.read_csv('telecom_customer_churn.csv')

In [ ]:
churn_data.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [ ]:
df = churn_data.copy()

In [ ]:
churn_data.dtypes

Customer ID                           object
Gender                                object
Age                                    int64
Married                               object
Number of Dependents                   int64
City                                  object
Zip Code                               int64
Latitude                             float64
Longitude                            float64
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                 object
Phone Service                         object
Avg Monthly Long Distance Charges    float64
Multiple Lines                        object
Internet Service                      object
Internet Type                         object
Avg Monthly GB Download              float64
Online Security                       object
Online Backup                         object
Device Protection Plan                object
Premium Tech Support                  object
Streaming TV                          object
Streaming Movies                      object
Streaming Music                       object
Unlimited Data                        object
Contract                              object
Paperless Billing                     object
Payment Method                        object
Monthly Charge                       float64
Total Charges                        float64
Total Refunds                        float64
Total Extra Data Charges               int64
Total Long Distance Charges          float64
Total Revenue                        float64
Customer Status                       object
Churn Category                        object
Churn Reason                          object
dtype: object

In [ ]:
churn_data.shape

(7043, 38)

In [ ]:
churn_data.isna().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                     1526
Streaming Music                      1526
Unlimited Data                       1526
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Customer Status                         0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [ ]:
## convert the name of columns into lowercase
churn_data.columns = churn_data.columns.str.lower()

In [ ]:
churn_data.columns = churn_data.columns.str.replace(' ', '_', regex=False)

In [ ]:
churn_data.head()

,customer_id,gender,age,married,number_of_dependents,city,zip_code,latitude,longitude,number_of_referrals,...,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,customer_status,churn_category,churn_reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [ ]:
columns_to_convert = ['phone_service',
 'married',
 'multiple_lines',
 'internet_service',
 'online_security',
 'online_backup',
 'device_protection_plan',
 'premium_tech_support',
 'streaming_tv',
 'streaming_music',
 'unlimited_data',
 'paperless_billing' ,'streaming_movies']

In [ ]:
churn_data[columns_to_convert] = churn_data[columns_to_convert].replace({'Yes':1, 'No':0})

In [ ]:
churn_data['gender'] = churn_data['gender'].replace({'Female':0, 'Male':1})

/tmp/ipykernel_5508/2222458095.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  churn_data['gender'] = churn_data['gender'].replace({'Female':0, 'Male':1})

In [ ]:
churn_data.head()

,customer_id,gender,age,married,number_of_dependents,city,zip_code,latitude,longitude,number_of_referrals,...,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,customer_status,churn_category,churn_reason
0,0002-ORFBO,0,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,1,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,1,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,1,78,1,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,0,75,1,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [ ]:
churn_data.isna().sum()

customer_id                             0
gender                                  0
age                                     0
married                                 0
number_of_dependents                    0
city                                    0
zip_code                                0
latitude                                0
longitude                               0
number_of_referrals                     0
tenure_in_months                        0
offer                                3877
phone_service                           0
avg_monthly_long_distance_charges     682
multiple_lines                        682
internet_service                        0
internet_type                        1526
avg_monthly_gb_download              1526
online_security                      1526
online_backup                        1526
device_protection_plan               1526
premium_tech_support                 1526
streaming_tv                         1526
streaming_movies                     1526
streaming_music                      1526
unlimited_data                       1526
contract                                0
paperless_billing                       0
payment_method                          0
monthly_charge                          0
total_charges                           0
total_refunds                           0
total_extra_data_charges                0
total_long_distance_charges             0
total_revenue                           0
customer_status                         0
churn_category                       5174
churn_reason                         5174
dtype: int64

In [ ]:
missing_value_columns =  ['offer','avg_monthly_long_distance_charges','multiple_lines','internet_type','avg_monthly_gb_download','online_security','online_backup','device_protection_plan','premium_tech_support','streaming_tv','streaming_movies','streaming_music','unlimited_data','churn_category','churn_reason']

In [ ]:
churn_data['offer'] = churn_data['offer'].fillna('No Offer')

In [ ]:
churn_data

,customer_id,gender,age,married,number_of_dependents,city,zip_code,latitude,longitude,number_of_referrals,...,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,customer_status,churn_category,churn_reason
0,0002-ORFBO,0,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,1,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,1,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,1,78,1,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,0,75,1,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,0,20,0,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,Stayed,NaN,NaN
7039,9992-RRAMN,1,40,1,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,1,22,0,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.00,0,37.24,129.99,Joined,NaN,NaN
7041,9993-LHIEB,1,21,1,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,Stayed,NaN,NaN
7042,9995-HOTOH,1,36,1,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,Stayed,NaN,NaN

In [ ]:
churn_data.loc[churn_data["phone_service"].eq("0") & churn_data["multiple_lines"].isna(), "multiple_lines"] = 0
churn_data.loc[churn_data["phone_service"].eq("0") & churn_data["avg_monthly_long_distance_charges"].isna(), "avg_monthly_long_distance_charges"] = 0

In [ ]:
churn_data[missing_value_columns]

,offer,avg_monthly_long_distance_charges,multiple_lines,internet_type,avg_monthly_gb_download,online_security,online_backup,device_protection_plan,premium_tech_support,streaming_tv,streaming_movies,streaming_music,unlimited_data,churn_category,churn_reason
0,No Offer,42.39,0.0,Cable,16.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,NaN,NaN
1,No Offer,10.69,1.0,Cable,10.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN
2,Offer E,33.65,0.0,Fiber Optic,30.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,Competitor,Competitor had better devices
3,Offer D,27.82,0.0,Fiber Optic,4.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,Dissatisfaction,Product dissatisfaction
4,No Offer,7.38,0.0,Fiber Optic,11.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Offer D,46.68,0.0,DSL,59.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,NaN,NaN
7039,Offer D,16.20,1.0,Fiber Optic,17.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,Dissatisfaction,Product dissatisfaction
7040,Offer E,18.62,0.0,DSL,51.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN
7041,Offer A,2.12,0.0,Cable,58.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,NaN,NaN
7042,No Offer,NaN,NaN,Cable,5.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN

In [ ]:
churn_data[['avg_monthly_gb_download','internet_service']]

      avg_monthly_gb_download  internet_service
0                        16.0                 1
1                        10.0                 1
2                        30.0                 1
3                         4.0                 1
4                        11.0                 1
...                       ...               ...
7038                     59.0                 1
7039                     17.0                 1
7040                     51.0                 1
7041                     58.0                 1
7042                      5.0                 1

[7043 rows x 2 columns]

In [ ]:
internet_columns = [
    "internet_type", "avg_monthly_gb_download", "online_security", "online_backup",
    "device_protection_plan", "premium_tech_support", "streaming_tv",
    "streaming_movies", "streaming_music", "unlimited_data","internet_service"
]

In [ ]:
for col in internet_columns:
    churn_data.loc[churn_data["internet_service"].eq(0) & churn_data[col].isna(), col] = 0

In [ ]:
churn_data[internet_columns]

,internet_type,avg_monthly_gb_download,online_security,online_backup,device_protection_plan,premium_tech_support,streaming_tv,streaming_movies,streaming_music,unlimited_data,internet_service
0,Cable,16.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1
1,Cable,10.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1
2,Fiber Optic,30.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1
3,Fiber Optic,4.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1
4,Fiber Optic,11.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...
7038,DSL,59.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1
7039,Fiber Optic,17.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1
7040,DSL,51.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1
7041,Cable,58.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1
7042,Cable,5.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1

In [ ]:
churn_data[['internet_service','streaming_tv']]

      internet_service  streaming_tv
0                    1           1.0
1                    1           0.0
2                    1           0.0
3                    1           1.0
4                    1           1.0
...                ...           ...
7038                 1           0.0
7039                 1           0.0
7040                 1           0.0
7041                 1           0.0
7042                 1           1.0

[7043 rows x 2 columns]

In [ ]:
df.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [ ]:
df[['Internet Service','Streaming TV']]

     Internet Service Streaming TV
0                 Yes          Yes
1                 Yes           No
2                 Yes           No
3                 Yes          Yes
4                 Yes          Yes
...               ...          ...
7038              Yes           No
7039              Yes           No
7040              Yes           No
7041              Yes           No
7042              Yes          Yes

[7043 rows x 2 columns]

In [ ]:
missing_value_columns

['offer',
 'avg_monthly_long_distance_charges',
 'multiple_lines',
 'internet_type',
 'avg_monthly_gb_download',
 'online_security',
 'online_backup',
 'device_protection_plan',
 'premium_tech_support',
 'streaming_tv',
 'streaming_movies',
 'streaming_music',
 'unlimited_data',
 'churn_category',
 'churn_reason']

In [ ]:
churn_data.isna().sum()

customer_id                             0
gender                                  0
age                                     0
married                                 0
number_of_dependents                    0
city                                    0
zip_code                                0
latitude                                0
longitude                               0
number_of_referrals                     0
tenure_in_months                        0
offer                                   0
phone_service                           0
avg_monthly_long_distance_charges     682
multiple_lines                        682
internet_service                        0
internet_type                           0
avg_monthly_gb_download                 0
online_security                         0
online_backup                           0
device_protection_plan                  0
premium_tech_support                    0
streaming_tv                            0
streaming_movies                        0
streaming_music                         0
unlimited_data                          0
contract                                0
paperless_billing                       0
payment_method                          0
monthly_charge                          0
total_charges                           0
total_refunds                           0
total_extra_data_charges                0
total_long_distance_charges             0
total_revenue                           0
customer_status                         0
churn_category                       5174
churn_reason                         5174
dtype: int64

In [ ]:
churn_data[['customer_status','churn_category','churn_reason']]

     customer_status   churn_category                   churn_reason
0             Stayed              NaN                            NaN
1             Stayed              NaN                            NaN
2            Churned       Competitor  Competitor had better devices
3            Churned  Dissatisfaction        Product dissatisfaction
4            Churned  Dissatisfaction            Network reliability
...              ...              ...                            ...
7038          Stayed              NaN                            NaN
7039         Churned  Dissatisfaction        Product dissatisfaction
7040          Joined              NaN                            NaN
7041          Stayed              NaN                            NaN
7042          Stayed              NaN                            NaN

[7043 rows x 3 columns]

In [ ]:
## select customers who did not churn and whose category is missing
churn_data.loc[churn_data["customer_status"].ne("Churned") & churn_data["churn_category"].isna(), "churn_category"] = "Not Churned"
churn_data.loc[churn_data["customer_status"].ne("Churned") & churn_data["churn_reason"].isna(), "churn_reason"] = "Not Churned"

In [ ]:
churn_data[missing_value_columns].isna().sum()

offer                                0
avg_monthly_long_distance_charges    0
multiple_lines                       0
internet_type                        0
avg_monthly_gb_download              0
online_security                      0
online_backup                        0
device_protection_plan               0
premium_tech_support                 0
streaming_tv                         0
streaming_movies                     0
streaming_music                      0
unlimited_data                       0
churn_category                       0
churn_reason                         0
dtype: int64

In [ ]:
churn_data["multiple_lines"] = churn_data["multiple_lines"].fillna("0")

In [ ]:
churn_data["avg_monthly_long_distance_charges"] = (
    churn_data.groupby("phone_service")["avg_monthly_long_distance_charges"]
      .transform(lambda x: x.fillna(0) if x.name == 0 else x.fillna(x.median()))
)

In [ ]:
## Now the data is clean, now we can upload it on sql for solving the queries
churn_data.to_csv("telecom_customer_churn_cleaned.csv", index=False)

In [ ]:
churn_data.head()

,customer_id,gender,age,married,number_of_dependents,city,zip_code,latitude,longitude,number_of_referrals,...,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,customer_status,churn_category,churn_reason
0,0002-ORFBO,0,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,Not Churned,Not Churned
1,0003-MKNFE,1,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,Not Churned,Not Churned
2,0004-TLHLJ,1,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,1,78,1,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,0,75,1,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability