<a href="https://colab.research.google.com/github/Meemansha-spec/EDA-with-Pandas/blob/main/Churn_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
from overrides.typing_utils import unknown

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [39]:
churn_data = pd.read_csv('telecom_customer_churn.csv')

In [40]:
churn_data.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [41]:
# Made the copy of dataset (just for keeping the original data intact)
df = churn_data.copy()

In [8]:
# check the data types in our dataset
churn_data.dtypes

Customer ID                           object
Gender                                object
Age                                    int64
Married                               object
Number of Dependents                   int64
City                                  object
Zip Code                               int64
Latitude                             float64
Longitude                            float64
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                 object
Phone Service                         object
Avg Monthly Long Distance Charges    float64
Multiple Lines                        object
Internet Service                      object
Internet Type                         object
Avg Monthly GB Download              float64
Online Security                       object
Online Backup                         object
Device Protection Plan                object
Premium Tech Support                  object
Streaming TV                          object
Streaming Movies                      object
Streaming Music                       object
Unlimited Data                        object
Contract                              object
Paperless Billing                     object
Payment Method                        object
Monthly Charge                       float64
Total Charges                        float64
Total Refunds                        float64
Total Extra Data Charges               int64
Total Long Distance Charges          float64
Total Revenue                        float64
Customer Status                       object
Churn Category                        object
Churn Reason                          object
dtype: object

In [11]:
#Description of dataset
churn_data.describe()

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,6361.000000,5517.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,1.951867,32.386767,25.420517,26.189958,63.596131,2280.381264,1.962182,6.860713,749.099262,3034.379056
std,16.750352,0.962802,1856.767505,2.468929,2.154425,3.001199,24.542061,14.200374,19.586585,31.204743,2266.220462,7.902614,25.104978,846.660055,2865.204542
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,0.000000,1.000000,1.010000,2.000000,-10.000000,18.800000,0.000000,0.000000,0.000000,21.360000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,0.000000,9.000000,13.050000,13.000000,30.400000,400.150000,0.000000,0.000000,70.545000,605.610000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,0.000000,29.000000,25.690000,21.000000,70.050000,1394.550000,0.000000,0.000000,401.440000,2108.640000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,3.000000,55.000000,37.680000,30.000000,89.750000,3786.600000,0.000000,0.000000,1191.100000,4801.145000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000

In [12]:
#find the missing values
churn_data.isna().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                     1526
Streaming Music                      1526
Unlimited Data                       1526
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Customer Status                         0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [42]:
## convert the name of columns into lowercase so that it becomes easy to retrieve the columns
churn_data.columns = churn_data.columns.str.lower()

In [45]:
churn_data.columns = churn_data.columns.str.replace(' ', '_', regex=False)

In [46]:
churn_data.head()

,customer_id,gender,age,married,number_of_dependents,city,zip_code,latitude,longitude,number_of_referrals,...,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,customer_status,churn_category,churn_reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [47]:
## We will convert yes and no columns to 1 and 0.
columns_to_convert = ['phone_service',
 'married',
 'multiple_lines',
 'internet_service',
 'online_security',
 'online_backup',
 'device_protection_plan',
 'premium_tech_support',
 'streaming_tv',
 'streaming_music',
 'unlimited_data',
 'paperless_billing' ,'streaming_movies']

In [48]:
churn_data[columns_to_convert] = churn_data[columns_to_convert].replace({'Yes':1, 'No':0})

/tmp/ipykernel_1592/3175654185.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  churn_data[columns_to_convert] = churn_data[columns_to_convert].replace({'Yes':1, 'No':0})

In [49]:
#convert male and female to 1 and 0
churn_data['gender'] = churn_data['gender'].replace({'Female':0, 'Male':1})

/tmp/ipykernel_1592/1949619748.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  churn_data['gender'] = churn_data['gender'].replace({'Female':0, 'Male':1})

In [50]:
## Here is the list of columns which are missing and we have to carefully fill them
missing_value_columns =  ['offer','avg_monthly_long_distance_charges','multiple_lines','internet_type','avg_monthly_gb_download','online_security','online_backup','device_protection_plan','premium_tech_support','streaming_tv','streaming_movies','streaming_music','unlimited_data','churn_category','churn_reason']

### Let's start filling the missing columns

In [51]:
churn_data['offer'] = churn_data['offer'].fillna('No Offer')

In [60]:
#where internet service is 0 make all the columns
internet_columns = [
    "online_security", "online_backup",
    "device_protection_plan", "premium_tech_support", "streaming_tv",
    "streaming_movies", "streaming_music", "unlimited_data","internet_service"
]

In [61]:
churn_data[internet_columns]

,online_security,online_backup,device_protection_plan,premium_tech_support,streaming_tv,streaming_movies,streaming_music,unlimited_data,internet_service
0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1
1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1
3,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1
4,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...
7038,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1
7039,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1
7040,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1
7041,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1
7042,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1

In [62]:
for col in internet_columns:
    churn_data.loc[churn_data["internet_service"].eq(0) & churn_data[col].isna(), col] = 0

In [52]:
## select customers who did not churn and marked their mising category as not churned.
churn_data.loc[churn_data["customer_status"].ne("Churned") & churn_data["churn_category"].isna(), "churn_category"] = "Not Churned"
churn_data.loc[churn_data["customer_status"].ne("Churned") & churn_data["churn_reason"].isna(), "churn_reason"] = "Not Churned"

In [55]:
# we can fill the missing multiple lines as where phone service is 0 , make multiple lines 0 and where phone service is 1, multiple lines 1
churn_data["multiple_lines"] = (
    churn_data.groupby("phone_service")["multiple_lines"]
      .transform(lambda x: 0 if x.name == 0 else 1)
)

In [56]:
# do same for avg long calls
churn_data["avg_monthly_long_distance_charges"] = (
    churn_data.groupby("phone_service")["avg_monthly_long_distance_charges"]
      .transform(lambda x: x.fillna(0) if x.name == 0 else x.fillna(x.median()))
)

In [64]:
churn_data.isna().sum()

customer_id                             0
gender                                  0
age                                     0
married                                 0
number_of_dependents                    0
city                                    0
zip_code                                0
latitude                                0
longitude                               0
number_of_referrals                     0
tenure_in_months                        0
offer                                   0
phone_service                           0
avg_monthly_long_distance_charges       0
multiple_lines                          0
internet_service                        0
internet_type                        1526
avg_monthly_gb_download              1526
online_security                         0
online_backup                           0
device_protection_plan                  0
premium_tech_support                    0
streaming_tv                            0
streaming_movies                        0
streaming_music                         0
unlimited_data                          0
contract                                0
paperless_billing                       0
payment_method                          0
monthly_charge                          0
total_charges                           0
total_refunds                           0
total_extra_data_charges                0
total_long_distance_charges             0
total_revenue                           0
customer_status                         0
churn_category                          0
churn_reason                            0
dtype: int64

In [65]:
churn_data["avg_monthly_gb_download"] = (
    churn_data.groupby("internet_service")["avg_monthly_gb_download"]
      .transform(lambda x: x.fillna(0) if x.name == 0 else x.fillna(x.median()))
)

In [67]:
churn_data['internet_type'] = churn_data['internet_type'].fillna('No Internet Service')

In [68]:
churn_data.isna().sum()

customer_id                          0
gender                               0
age                                  0
married                              0
number_of_dependents                 0
city                                 0
zip_code                             0
latitude                             0
longitude                            0
number_of_referrals                  0
tenure_in_months                     0
offer                                0
phone_service                        0
avg_monthly_long_distance_charges    0
multiple_lines                       0
internet_service                     0
internet_type                        0
avg_monthly_gb_download              0
online_security                      0
online_backup                        0
device_protection_plan               0
premium_tech_support                 0
streaming_tv                         0
streaming_movies                     0
streaming_music                      0
unlimited_data                       0
contract                             0
paperless_billing                    0
payment_method                       0
monthly_charge                       0
total_charges                        0
total_refunds                        0
total_extra_data_charges             0
total_long_distance_charges          0
total_revenue                        0
customer_status                      0
churn_category                       0
churn_reason                         0
dtype: int64

In [71]:
## Now the data is clean, now we can upload it on sql for solving the queries
churn_data.to_csv("telecom_customer_churn_cleaned.csv", index=False)

## The Data is cleaned